# Generated by Django 5.2.11 on 2026-03-05 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_jwt_authentication'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='revokedtoken',
            new_name='users_revok_token_i_d4f5f3_idx',
            old_name='users_revoke_token_i_idx',
        ),
        migrations.RenameIndex(
            model_name='revokedtoken',
            new_name='users_revok_user_id_ed1586_idx',
            old_name='users_revoke_user_id_revoked_idx',
        ),
        migrations.RenameIndex(
            model_name='userloginhistory',
            new_name='users_userl_user_id_b5dceb_idx',
            old_name='users_userlo_user_id_login__idx',
        ),
    ]
