# Generated by Django 5.2.11 on 2026-02-24 00:47

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('data_nascimento', models.DateField()),
                ('cartao_sus', models.CharField(max_length=18, unique=True)),
                ('raca', models.CharField(choices=[('branca', 'Branca'), ('preta', 'Preta'), ('parda', 'Parda'), ('asiatica', 'Asiática'), ('indigena', 'Indígena'), ('nao_declarado', 'Não Declarado')], max_length=20)),
                ('cor', models.CharField(choices=[('branca', 'Branca'), ('preta', 'Preta'), ('amarela', 'Amarela'), ('parda', 'Parda'), ('indigena', 'Indígena')], max_length=20)),
                ('sexualidade', models.CharField(choices=[('heterosexual', 'Heterossexual'), ('homossexual', 'Homossexual'), ('bissexual', 'Bissexual'), ('asexual', 'Assexual'), ('prefiro_nao_responder', 'Prefiro não responder')], max_length=30)),
                ('escolaridade', models.CharField(choices=[('sem_escolaridade', 'Sem Escolaridade'), ('ensino_fundamental', 'Ensino Fundamental'), ('ensino_medio', 'Ensino Médio'), ('ensino_superior', 'Ensino Superior'), ('pos_graduacao', 'Pós-Graduação'), ('nao_declarado', 'Não Declarado')], max_length=30)),
                ('rua', models.CharField(max_length=255)),
                ('bairro', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=2)),
                ('cep', models.CharField(max_length=9)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoSexual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idade_inicio_atividade_sexual', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('numero_parceiros', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)])),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='historico_sexual', to='pacientes.paciente')),
            ],
            options={
                'verbose_name_plural': 'Históricos Sexuais',
            },
        ),
        migrations.CreateModel(
            name='HistoricoReprodutivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_gestacoes', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('historico_ists', models.TextField(blank=True, help_text='Descreva o histórico de Infecções Sexualmente Transmissíveis (ISTs) anteriores', null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='historico_reprodutivo', to='pacientes.paciente')),
            ],
            options={
                'verbose_name_plural': 'Históricos Reprodutivos',
            },
        ),
        migrations.CreateModel(
            name='ExameDnaHpv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_exame', models.DateField()),
                ('tipo_hpv', models.CharField(choices=[('16', 'HPV 16 (Alto Risco)'), ('18', 'HPV 18 (Alto Risco)'), ('31', 'HPV 31 (Alto Risco)'), ('33', 'HPV 33 (Alto Risco)'), ('45', 'HPV 45 (Alto Risco)'), ('6', 'HPV 6 (Baixo Risco)'), ('11', 'HPV 11 (Baixo Risco)'), ('outro', 'Outro Tipo'), ('negativo', 'Negativo para HPV')], max_length=50)),
                ('carga_viral', models.CharField(blank=True, max_length=100, null=True)),
                ('resultado', models.CharField(max_length=50)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exames_dna_hpv', to='pacientes.paciente')),
            ],
            options={
                'verbose_name': 'Exame DNA-HPV',
                'verbose_name_plural': 'Exames DNA-HPV',
                'ordering': ['-data_exame'],
            },
        ),
        migrations.CreateModel(
            name='CitopatologicoHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_exame', models.DateField()),
                ('resultado', models.CharField(choices=[('normal', 'Normal'), ('mudancas_reativas', 'Mudanças Reativas'), ('nic1', 'NIC I'), ('nic2', 'NIC II'), ('nic3', 'NIC III'), ('cancer', 'Câncer'), ('nao_conclusivo', 'Não Conclusivo')], max_length=50)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citopatologicos', to='pacientes.paciente')),
            ],
            options={
                'verbose_name_plural': 'Citopatológicos',
                'ordering': ['-data_exame'],
            },
        ),
        migrations.CreateModel(
            name='ProcedimentoRealizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_procedimento', models.CharField(choices=[('colposcopia', 'Colposcopia'), ('biopsia', 'Biópsia'), ('conizacao', 'Conização'), ('laser', 'Laser'), ('crioterapia', 'Crioterapia'), ('leep', 'LEEP'), ('outro', 'Outro')], max_length=50)),
                ('data_procedimento', models.DateField()),
                ('resultado', models.TextField()),
                ('complicacoes', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedimentos', to='pacientes.paciente')),
            ],
            options={
                'ordering': ['-data_procedimento'],
            },
        ),
        migrations.CreateModel(
            name='StatusSeguimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('pausado', 'Pausado'), ('inativo', 'Inativo')], max_length=20)),
                ('proxima_consulta', models.DateField(blank=True, null=True)),
                ('adesao_cronograma', models.BooleanField(default=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='status_seguimento', to='pacientes.paciente')),
            ],
            options={
                'verbose_name_plural': 'Status de Seguimento',
            },
        ),
        migrations.CreateModel(
            name='Vacinacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_vacinacao', models.CharField(choices=[('nao_vacinado', 'Não Vacinado'), ('parcialmente_vacinado', 'Parcialmente Vacinado'), ('totalmente_vacinado', 'Totalmente Vacinado')], max_length=30)),
                ('data_primeira_dose', models.DateField(blank=True, null=True)),
                ('data_segunda_dose', models.DateField(blank=True, null=True)),
                ('data_terceira_dose', models.DateField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vacinacao', to='pacientes.paciente')),
            ],
        ),
    ]
