# Generated by Django 5.2.11 on 2026-02-24 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='sexualidade',
            field=models.CharField(choices=[('heterosexual', 'Heterossexual'), ('homossexual', 'Homossexual'), ('bissexual', 'Bissexual'), ('asexual', 'Assexual'), ('transsexual', 'Transsexual'), ('prefiro_nao_responder', 'Prefiro não responder')], max_length=30),
        ),
    ]
