# Generated by Django 5.2.11 on 2026-02-24 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0002_alter_paciente_sexualidade'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='statusseguimento',
            options={'verbose_name_plural': 'Classificação de Risco'},
        ),
        migrations.RemoveField(
            model_name='statusseguimento',
            name='adesao_cronograma',
        ),
        migrations.RemoveField(
            model_name='statusseguimento',
            name='observacoes',
        ),
        migrations.RemoveField(
            model_name='statusseguimento',
            name='proxima_consulta',
        ),
        migrations.RemoveField(
            model_name='statusseguimento',
            name='status',
        ),
        migrations.AddField(
            model_name='statusseguimento',
            name='classificacao_risco',
            field=models.CharField(blank=True, choices=[('baixo', 'Baixo Risco'), ('medio', 'Médio Risco'), ('alto', 'Alto Risco')], max_length=10, null=True),
        ),
    ]
