# Generated by Django 5.2.11 on 2026-02-24 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0003_alter_statusseguimento_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='raca',
        ),
        migrations.AlterField(
            model_name='paciente',
            name='cor',
            field=models.CharField(choices=[('branca', 'Branca'), ('preta', 'Preta'), ('amarela', 'Amarela'), ('parda', 'Parda'), ('indigena', 'Indígena')], max_length=20, verbose_name='Grupo étnico'),
        ),
    ]
