# Generated by Django 5.2.11 on 2026-02-24 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0004_remove_paciente_raca_alter_paciente_cor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='cor',
            field=models.CharField(choices=[('branca', 'Branca'), ('preta', 'Preta'), ('amarela', 'Amarela'), ('parda', 'Parda'), ('indigena', 'Indígena'), ('outro', 'Outro'), ('nao_declarado', 'Não Declarado')], max_length=20, verbose_name='Grupo étnico'),
        ),
    ]
