# Generated by Django 5.2.11 on 2026-02-24 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedIA', '0001_initial'),
        ('pacientes', '0005_alter_paciente_cor'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassificacaoHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_classificacao', models.DateTimeField(auto_now_add=True)),
                ('risco_ia', models.CharField(help_text='Classificação original da IA', max_length=10)),
                ('risco_final', models.CharField(help_text='Classificação final após NER', max_length=10)),
                ('modificador_ner', models.IntegerField(default=0, help_text='Modificador aplicado pelo NER (-1, 0, +1)')),
                ('hpv_types', models.JSONField(blank=True, default=list)),
                ('lesions', models.JSONField(blank=True, default=list)),
                ('exams', models.JSONField(blank=True, default=list)),
                ('procedures', models.JSONField(blank=True, default=list)),
                ('viral_loads', models.JSONField(blank=True, default=list)),
                ('texto_original', models.TextField(blank=True)),
                ('texto_enriquecido', models.TextField(blank=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_classificacoes', to='pacientes.paciente')),
            ],
            options={
                'verbose_name': 'Histórico de Classificação',
                'verbose_name_plural': 'Históricos de Classificação',
                'ordering': ['-data_classificacao'],
            },
        ),
    ]
